services:
  api:
    build:
      context: .
      target: development
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG}
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    environment:
      - CONFIG_FILE=/run/secrets/config.json
    secrets:
      - config.json
    deploy:
      resources:
        limits:
          cpus: '4'
secrets:
  config.json:
    file: config.json