services:
  api:
    build:
      context: .
      target: development
      args:
        GO_VERSION: ${GO_VERSION}
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - ${ENV_FILE}


    