services:
  api:
    build:
      context: .
      target: production
      args:
        GO_VERSION: ${GO_VERSION}
    volumes:
      - db:/app/db
    ports:
      - 8080:8080
    env_file:
      - ${ENV_FILE}

volumes:
  db: