services:
  api:
    build:
      context: .
      target: development
      args:
        GO_VERSION: ${GO_VERSION}
        IMAGE_OS_NAME: ${IMAGE_OS_NAME}
        IMAGE_OS_VERSION: ${IMAGE_OS_VERSION}
    volumes:
      - .:/app
    ports:
      - 8080:${PORT}
    env_file:
      - ${ENV_FILE}
