services:
  api:
    build:
      context: .
      target: dev
      args:
        GO_VERSION: ${GO_VERSION}
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ${ENV_FILE}


    