services:
  api:
    build:
      context: .
      target: development
      args:
        GO_VERSION: ${GO_VERSION}
    container_name: api
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ${ENV_FILE}


    