// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      *string            `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Subscription struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	AccountID pgtype.UUID        `db:"account_id" json:"account_id"`
	PlanID    string             `db:"plan_id" json:"plan_id"`
	Status    string             `db:"status" json:"status"`
	StartsAt  pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt    pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Username   *string            `db:"username" json:"username"`
	Email      string             `db:"email" json:"email"`
	VerifiedAt pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserAccount struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	AccountID pgtype.UUID        `db:"account_id" json:"account_id"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
