// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otps.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOtp = `-- name: CreateOtp :exec
INSERT INTO otps (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateOtpParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CodeHash  []byte             `db:"code_hash" json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateOtp(ctx context.Context, arg CreateOtpParams) error {
	_, err := q.db.Exec(ctx, createOtp, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	return err
}

const deleteOtp = `-- name: DeleteOtp :exec
DELETE FROM otps
WHERE id = $1
`

func (q *Queries) DeleteOtp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOtp, id)
	return err
}

const getOtpByUserId = `-- name: GetOtpByUserId :one
SELECT id, user_id, code_hash, attempts, consumed_at, expires_at, created_at, updated_at FROM otps
WHERE user_id = $1
AND consumed_at IS NULL
AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetOtpByUserId(ctx context.Context, userID pgtype.UUID) (*Otp, error) {
	row := q.db.QueryRow(ctx, getOtpByUserId, userID)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Attempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const incrementOtpAttempts = `-- name: IncrementOtpAttempts :exec
UPDATE otps
SET attempts = attempts + 1
WHERE user_id = $1
`

func (q *Queries) IncrementOtpAttempts(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOtpAttempts, userID)
	return err
}
