// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions(user_id,user_agent,ip_address,expires_at)
VALUES ($1,$2,$3,$4)
RETURNING id
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	UserAgent *string            `db:"user_agent" json:"user_agent"`
	IpAddress netip.Addr         `db:"ip_address" json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserBySessionId = `-- name: GetUserBySessionId :one
SELECT u.id, u.username, u.email, u.verified_at, u.created_at, u.updated_at FROM users AS u
JOIN sessions AS s ON u.id = s.user_id
WHERE s.id = $1
`

func (q *Queries) GetUserBySessionId(ctx context.Context, sessionID pgtype.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserBySessionId, sessionID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
