// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriptionByAccountID = `-- name: GetSubscriptionByAccountID :one
SELECT id, account_id, plan_id, status, starts_at, ends_at, created_at, updated_at FROM subscriptions WHERE account_id = $1
`

func (q *Queries) GetSubscriptionByAccountID(ctx context.Context, accountID pgtype.UUID) (*Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByAccountID, accountID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PlanID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
