// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAccountsByUserID = `-- name: GetUserAccountsByUserID :many
SELECT a.id, a.name, a.created_at, a.updated_at FROM accounts AS a JOIN user_accounts as ua ON ua.account_id = a.id WHERE ua.user_id = $1
`

func (q *Queries) GetUserAccountsByUserID(ctx context.Context, userID pgtype.UUID) ([]*Account, error) {
	rows, err := q.db.Query(ctx, getUserAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
