// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username)
VALUES ($1 , $2)
RETURNING id, username, email, verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email    string  `db:"email" json:"email"`
	Username *string `db:"username" json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUser, id)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Username  *string            `db:"username" json:"username"`
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Username *string     `db:"username" json:"username"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Username)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, created_at, updated_at
FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListUsersRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Username  *string            `db:"username" json:"username"`
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = COALESCE(NULLIF($1, ''), username),
    email = COALESCE(NULLIF($2, ''), email),
    verified_at = COALESCE($3, verified_at)
WHERE id = $4
RETURNING id, username, email, verified_at, created_at, updated_at
`

type UpdateUserParams struct {
	Username   interface{}        `db:"username" json:"username"`
	Email      interface{}        `db:"email" json:"email"`
	VerifiedAt pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	ID         pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.VerifiedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE
SET email = $1
RETURNING id, username, email, verified_at, created_at, updated_at
`

func (q *Queries) UpsertUser(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, upsertUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
