definitions:
  config.Client:
    properties:
      env:
        enum:
        - development
        - production
        type: string
      isDev:
        type: boolean
    required:
    - env
    type: object
  repo.User:
    properties:
      account_status:
        type: string
      created_at:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      full_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      image_url:
        type: string
      is_verified:
        type: boolean
      phone_number:
        type: string
      role:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Home page.
      responses:
        "200":
          description: home page
          schema:
            type: html
      summary: Home Page
  /_:
    get:
      description: Admin route.
      responses:
        "200":
          description: Admin page
          schema:
            type: string
        "401":
          description: invalid session
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Admin route
  /config:
    get:
      description: Get client config.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/config.Client'
      summary: Get config
  /me:
    get:
      description: Get user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo.User'
        "401":
          description: invalid session
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get user
  /ping:
    get:
      description: Ping the server.
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
swagger: "2.0"
