definitions:
  config.Client:
    properties:
      appEnv:
        enum:
        - development
        - production
        type: string
    required:
    - appEnv
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Home page.
      responses:
        "200":
          description: home page
          schema:
            type: html
      summary: Home Page
  /_:
    get:
      description: Admin route.
      responses:
        "200":
          description: Admin page
          schema:
            type: string
        "401":
          description: invalid session
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Admin route
  /config:
    get:
      description: Get client config.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/config.Client'
      summary: Get config
  /ping:
    get:
      description: Ping the server.
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
swagger: "2.0"
