definitions:
  handler.response:
    properties:
      message:
        type: string
    type: object
  repo.User:
    properties:
      accountStatus:
        type: string
      createdAt:
        type: string
      dateOfBirth:
        type: string
      email:
        type: string
      gender:
        type: string
      id:
        type: integer
      imageUrl:
        type: string
      passwordHash:
        type: string
      role:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Home page.
      responses:
        "200":
          description: home page
          schema:
            type: html
      summary: Home Page
  /_:
    get:
      description: Admin route.
      responses:
        "200":
          description: Admin page
          schema:
            type: string
        "401":
          description: invalid session
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Admin route
  /auth/access-token:
    get:
      consumes:
      - application/json
      description: Get access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Get access token
      tags:
      - Auth
  /auth/change-password:
    post:
      consumes:
      - application/json
      description: Change password
      parameters:
      - description: Current password
        in: formData
        name: currentPassword
        required: true
        type: string
      - description: New password
        in: formData
        name: newPassword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Change password
      tags:
      - Auth
  /auth/log-in:
    post:
      consumes:
      - application/json
      description: Log in
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Log in
      tags:
      - Auth
  /auth/logout:
    get:
      consumes:
      - application/json
      description: Log out
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Log out
      tags:
      - Auth
  /auth/reset-password:
    get:
      consumes:
      - application/json
      description: Reset password
      parameters:
      - description: Token
        in: formData
        name: token
        required: true
        type: string
      - description: New password
        in: formData
        name: newPassword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Reset password
      tags:
      - Auth
    post:
      consumes:
      - application/json
      description: Send reset password email
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Callback URL
        in: formData
        name: callbackURL
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Send reset password email
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Sign up
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Sign up
      tags:
      - Auth
  /auth/verify-account:
    get:
      consumes:
      - application/json
      description: Verify account
      parameters:
      - description: Token
        in: formData
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Verify account
      tags:
      - Auth
    post:
      consumes:
      - application/json
      description: Send account verification email
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.response'
      summary: Send account verification email
      tags:
      - Auth
  /config:
    get:
      description: Get client config.
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get config
  /me:
    get:
      description: Get user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo.User'
        "401":
          description: invalid session
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get user
swagger: "2.0"
