name: Deploy docker image to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: env

      - name: Push Docker image to Docker Hub
        run: docker push ${{secrets.DOCKERHUB_REPO_NAME}}:${{ github.sha }}

      - name: Tag and Push Docker image as latest
        run: |
          docker tag ${{secrets.DOCKERHUB_REPO_NAME}}:${{ github.sha }} ${{secrets.DOCKERHUB_REPO_NAME}}:latest
          docker push ${{secrets.DOCKERHUB_REPO_NAME}}:latest